on: push
name: Build
jobs:
  releases:
    name: Release APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter --version
    - run: flutter doctor
    - run: flutter pub get
    - run: flutter test
    
    - run: flutter build web
    # Push web app to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web
    
    - run: flutter build apk --split-per-abi
    - run: flutter build appbundle
    # Push the android builds to workflow page
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Android
        path: build/app/outputs/flutter-apk/*.apk