on: push
name: Build
jobs:
  releases:
    name: Release APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter --version
    - run: flutter doctor
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk --split-per-abi
    - run: flutter build appbundle